### ISSUE TITLE
springboot整合nutz-starter如何设置查询参数格式自动转换

### ISSUE THREAD

**Issue by KuoCHsiang** [nutzam/nutz-spring-boot-starter#6]
定义一个vo 使用自定义sql查询，数据库查询出来的字段为role_id， 如何不用每个参数进行格式转换 实现 role_id自动赋值到vo的roleId参数中。

**Comment by ywjno** [comment]
普通的代码的话`Daos.FORCE_HUMP_COLUMN_NAME = true`这样就行，或许需要在 `NutzDatabaseInitializer` 类里面添加这些配置项，要么就需要在vo里面每个都写`@Column(hump = true)`

**Comment by ywjno** [comment]
我在想要不自己写个`@Configuration`的配置类把 `Daos.FORCE_HUMP_COLUMN_NAME = true`这句话给加上

**Comment by Kerbores** [comment]
在项目的启动类里面加上这个就可以解决
`
    @Bean
    public CommandLineRunner commandLineRunner() {
        return new CommandLineRunner() {

            @Override
            public void run(String... args) throws Exception {
                Daos.FORCE_HUMP_COLUMN_NAME = true;
            }
        };
    }
`

**Comment by Kerbores** [comment]
后续版本考虑设置成application.yml配置文件可配置化
