### ISSUE TITLE
springboot 集成 nutz.dao 如何配置多数据源？

### ISSUE THREAD

**Issue by KerwinChen** [nutzam/nutz-spring-boot-starter#8]
请问使用了 nutz-spring-boot-starter 如何在 springboot 项目里面配置多数据源？
是需要重写 NutzDaoAutoConfiguration、NutzDaoAutoConfigurationProperties、NutzDatabaseInitializer 这三个类吗？
是否有 demo 能够参考一下。。

**Comment by Kerbores** [comment]
有两类方案:
+ aop实现数据源切换
需要按照以下思路实现:
1. 配置多个数据源
2. 实现一个aop对nutzDao实例的datasource进行设置切换
+ 配置两套Nutz相关的Bean
参考目前NutzDaoAutoConfiguration的方式注入多个nutzDao实例即可

**Comment by Kerbores** [comment]
Aop方案(模拟读写分离)伪代码如下:
1. druid配置多个数据源,bean的name为 ds1,ds2
2. 写一个注解DS
3. 写一个aop切面拦截DS注解
4. 读取DS注解的value,如ds1
5. 获取NutzDao类型的bean实例
6. 获取name为ds1的数据源bean实例
7. 调用NutzDao类型的bean实例的setDatasource方法,传入name为ds1的数据源bean实例
然后dao之上的层面基本无感切换数据源

**Comment by KerwinChen** [comment]
使用第二种方案配置的话，是不是没办法做到自动建表之类的操作了？
我尝试配置了两个 NutzDaoAutoConfigurationProperties，分别用 @ConfigurationProperties(prefix = "") 指向配置文件的两个 dao，默认还是会进入到 NutzDatabaseInitializer，然后就报错了。

**Comment by Kerbores** [comment]
> 使用第二种方案配置的话，是不是没办法做到自动建表之类的操作了？
> 我尝试配置了两个 NutzDaoAutoConfigurationProperties，分别用 @ConfigurationProperties(prefix = "") 指向配置文件的两个 dao，默认还是会进入到 NutzDatabaseInitializer，然后就报错了。

这个需要根据实际场景处理,如果仅仅是做读写分离的话可以让数据库自己去做同步.如果是其他场景可以将各个数据库对应的实体写到不同的包下,然后使用commandLineRunner进行扫包建表操作
